### PR TITLE
Initial support for Telegraf tagging format

### PR DESCRIPTION
**Pull request by AdamLeyshon**
Hello, Here is an implementation of the Statsd protocol that has support for Telegraf/InfluxDB Tagging,

It is fairly similar to that of DataDogs, but they are not compatible.

There is a new Protocol and Client.

### CODE REVIEW

**Comment by so1n** [comment]
Thank you for your submission, I will release the new version together after refining the test cases and testing

**Comment by AdamLeyshon** [comment]
No problem, let me know if anything needs adjusting, 
Might I also suggest adding Pre-Commit hooks such as Black and Flake8?

It would make reviewing pull requests significantly easier by ensuring minimal diffs due to formatting.

**Comment by so1n** [comment]
> No problem, let me know if anything needs adjusting,
> Might I also suggest adding Pre-Commit hooks such as Black and Flake8?
> 
> It would make reviewing pull requests significantly easier by ensuring minimal diffs due to formatting.

Thanks for your advice, I don't have much free time at the moment, but I will gradually improve the project

**Comment by so1n** [comment]
From the following url, I found that the metric generation rules of telegraf and dog statsd are not the same, I need to make changes and release to version 0.2.4
https://github.com/ToolSense/telegraf_pyplug
https://github.com/paksu/pytelegraf/blob/master/telegraf/protocol.py
https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/

**Comment by so1n** [comment]
Sorry, after reviewing the documentation I understand that you are submitting the telegraf input plugin statsd, not the telegraf input protocol (just like carbon and statsd)
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd

**Pull request merged**
